"""Current Shokrban / Iran Carbon Black production grades and ASTM quality specs."""

from __future__ import annotations

from typing import Any

# Active commercial grades currently in production (user-provided quality sheets).
CURRENT_PRODUCTS: list[dict[str, Any]] = [
    {
        "code": "N-326",
        "astm_code": "N326",
        "trade_name": "HAF-LS",
        "variant": "V-7",
        "classification": "HAF",
        "status": "in_production",
        "label_fa": "Carbon black N-326 — HAF-LS (V-7)",
        "description_fa": "Reinforcing grade with low structure (Low Structure) in the HAF family",
    },
    {
        "code": "N-234",
        "astm_code": "N234",
        "trade_name": "ISAF-HM-HS",
        "variant": "V-6",
        "classification": "ISAF",
        "status": "in_production",
        "label_fa": "Carbon black N-234 — ISAF-HM-HS (V-6)",
        "description_fa": "ISAF grade with high structure / high modulus for hard reinforcing applications",
    },
    {
        "code": "N-220",
        "astm_code": "N220",
        "trade_name": "ISAF-HM",
        "variant": None,
        "classification": "ISAF",
        "status": "in_production",
        "label_fa": "Carbon black N-220 — ISAF-HM",
        "description_fa": "Standard high-modulus ISAF grade; the main tire reinforcement product",
    },
    {
        "code": "P-8201",
        "astm_code": "P8201",
        "trade_name": "ICJ I.C.C",
        "variant": "V3",
        "classification": "Specialty",
        "status": "in_production",
        "label_fa": "Carbon black ICJ P-8201 — I.C.C (V3)",
        "description_fa": "Specialty ICJ / I.C.C grade for special industrial applications",
    },
    {
        "code": "N-330-SV",
        "astm_code": "N330",
        "trade_name": "S-V",
        "variant": "S-V",
        "classification": "HAF",
        "status": "in_production",
        "label_fa": "Carbon black N-330 — S-V",
        "description_fa": "N-330 grade with S-V variant specifications",
    },
    {
        "code": "N-660",
        "astm_code": "N660",
        "trade_name": "GPF S-SO",
        "variant": "S-SO",
        "classification": "GPF",
        "status": "in_production",
        "label_fa": "Carbon black N-660 — GPF (S-SO)",
        "description_fa": "GPF grade for general-purpose and filler applications",
    },
    {
        "code": "N-550-ICC",
        "astm_code": "N550",
        "trade_name": "FEF I.C.C S-SO",
        "variant": "S-SO",
        "classification": "FEF",
        "status": "in_production",
        "label_fa": "Carbon black N-550 — FEF I.C.C (S-SO)",
        "description_fa": "FEF grade with I.C.C / S-SO specifications",
    },
    {
        "code": "N-550-VJ",
        "astm_code": "N550",
        "trade_name": "V-J",
        "variant": "V-J",
        "classification": "FEF",
        "status": "in_production",
        "label_fa": "Carbon black N-550 — V-J",
        "description_fa": "N-550 grade with V-J variant",
    },
    {
        "code": "N-375",
        "astm_code": "N375",
        "trade_name": "HAF-HS",
        "variant": "V-M",
        "classification": "HAF",
        "status": "in_production",
        "label_fa": "Carbon black N-375 — HAF-HS (V-M)",
        "description_fa": "HAF grade with high structure (High Structure)",
    },
    {
        "code": "N-339",
        "astm_code": "N339",
        "trade_name": "HAF-HS",
        "variant": "V-3",
        "classification": "HAF",
        "status": "in_production",
        "label_fa": "Carbon black N-339 — HAF-HS (V-3)",
        "description_fa": "Standard HAF-HS grade for tires and rubber parts",
    },
    {
        "code": "N-330",
        "astm_code": "N330",
        "trade_name": "HAF",
        "variant": None,
        "classification": "HAF",
        "status": "in_production",
        "label_fa": "Carbon black N-330 — HAF",
        "description_fa": "Classic HAF grade N-330; widely used in the tire industry",
    },
]

# Order matches CURRENT_PRODUCTS:
# N-326, N-234, N-220, P-8201, N-330-SV, N-660, N-550-ICC, N-550-VJ, N-375, N-339, N-330
QUALITY_SPEC_ROWS: list[dict[str, Any]] = [
    {
        "id": "iodine_no",
        "label_en": "Iodine No.",
        "label_fa": "Iodine number",
        "unit": "mg/g",
        "astm": "D-1510",
        "values": [
            "77 / 87",
            "115 / 125",
            "116 / 126",
            "25 / 35",
            "75 / 90",
            "31 / 41",
            "38 / 48",
            "40 / 50",
            "85 / 95",
            "85 / 95",
            "77 / 87",
        ],
        "ranges": [
            (77.0, 87.0),
            (115.0, 125.0),
            (116.0, 126.0),
            (25.0, 35.0),
            (75.0, 90.0),
            (31.0, 41.0),
            (38.0, 48.0),
            (40.0, 50.0),
            (85.0, 95.0),
            (85.0, 95.0),
            (77.0, 87.0),
        ],
    },
    {
        "id": "oil_absorption_dbp",
        "label_en": "Oil Absorption Number (DBP)",
        "label_fa": "Oil absorption (DBP)",
        "unit": "ml/100g",
        "astm": "D-2414",
        "values": [
            "67 / 77",
            "120 / 130",
            "109 / 119",
            "95.0 / 110.0",
            "95 / 110",
            "85 / 95",
            "116 / 126",
            "110 / 125",
            "109 / 119",
            "115 / 125",
            "97 / 107",
        ],
        "ranges": [
            (67.0, 77.0),
            (120.0, 130.0),
            (109.0, 119.0),
            (95.0, 110.0),
            (95.0, 110.0),
            (85.0, 95.0),
            (116.0, 126.0),
            (110.0, 125.0),
            (109.0, 119.0),
            (115.0, 125.0),
            (97.0, 107.0),
        ],
    },
    {
        "id": "tint_strength",
        "label_en": "Tint Strength",
        "label_fa": "Tint strength",
        "unit": "%IRB#3",
        "astm": "D-3265",
        "values": [
            "106 / 116",
            "118 / 128",
            "111 / 121",
            "99.0 / 109.0",
            "99 / 109",
            "52 / 65",
            "58 / 68",
            "58 / 68",
            "109 / 119",
            "106 / 116",
            "99 / 109",
        ],
        "ranges": [
            (106.0, 116.0),
            (118.0, 128.0),
            (111.0, 121.0),
            (99.0, 109.0),
            (99.0, 109.0),
            (52.0, 65.0),
            (58.0, 68.0),
            (58.0, 68.0),
            (109.0, 119.0),
            (106.0, 116.0),
            (99.0, 109.0),
        ],
    },
    {
        "id": "pour_density",
        "label_en": "Pour Density",
        "label_fa": "Pour density",
        "unit": "Kg/m³",
        "astm": "D-1513",
        "values": [
            "455 ± 20",
            "320 ± 20",
            "355 ± 20",
            "350 / 375",
            "350 / 375",
            "440 ± 20",
            "360 ± 20",
            "330 / 355",
            "345 ± 20",
            "345 ± 20",
            "380 ± 20",
        ],
    },
    {
        "id": "toluene_discoloration",
        "label_en": "Toluene Solvent Discoloration",
        "label_fa": "Toluene discoloration",
        "unit": "T%",
        "astm": "D-1618",
        "values": [
            "MIN 85",
            "MIN 85",
            "MIN 85",
            "MIN 90",
            "MIN 90",
            "MIN 75",
            "MIN 75",
            "MIN 80",
            "MIN 85",
            "MIN 85",
            "MIN 85",
        ],
        "mins": [85.0, 85.0, 85.0, 90.0, 90.0, 75.0, 75.0, 80.0, 85.0, 85.0, 85.0],
    },
    {
        "id": "ph",
        "label_en": "pH",
        "label_fa": "pH",
        "unit": "—",
        "astm": "D-1512",
        "values": [
            "7.5 – 9",
            "7.5 – 9",
            "7.5 – 9",
            "6.0 – 10.0",
            "6.0 – 10.0",
            "7.5 – 9",
            "7.5 – 9",
            "6.0 – 10.0",
            "7.5 – 9",
            "7.5 – 9",
            "7.5 – 9",
        ],
        "ranges": [
            (7.5, 9.0),
            (7.5, 9.0),
            (7.5, 9.0),
            (6.0, 10.0),
            (6.0, 10.0),
            (7.5, 9.0),
            (7.5, 9.0),
            (6.0, 10.0),
            (7.5, 9.0),
            (7.5, 9.0),
            (7.5, 9.0),
        ],
    },
    {
        "id": "fines_content",
        "label_en": "Fines Content",
        "label_fa": "Fines content",
        "unit": "%",
        "astm": "D-1508",
        "values": [
            "MAX 10",
            "MAX 10",
            "MAX 10",
            "MAX 10",
            "MAX 15.0",
            "MAX 10",
            "MAX 10",
            "MAX 15.0",
            "MAX 10",
            "MAX 10",
            "MAX 10",
        ],
        "maxes": [10.0, 10.0, 10.0, 10.0, 15.0, 10.0, 10.0, 15.0, 10.0, 10.0, 10.0],
    },
    {
        "id": "heating_loss",
        "label_en": "Heating Loss",
        "label_fa": "Heat loss",
        "unit": "%",
        "astm": "D-1509",
        "values": [
            "MAX 1",
            "MAX 1",
            "MAX 1",
            "MAX 0.5",
            "MAX 0.5",
            "MAX 1",
            "MAX 1",
            "MAX 0.5",
            "MAX 1",
            "MAX 1",
            "MAX 1",
        ],
        "maxes": [1.0, 1.0, 1.0, 0.5, 0.5, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0],
    },
    {
        "id": "sieve_residue_325",
        "label_en": "Sieve Residue 325 Mesh",
        "label_fa": "325 mesh sieve residue",
        "unit": "ppm",
        "astm": "D-1514",
        "values": [
            "MAX 1000",
            "MAX 1000",
            "MAX 1000",
            "MAX 150",
            "MAX 200",
            "MAX 1000",
            "MAX 1000",
            "MAX 150",
            "MAX 1000",
            "MAX 1000",
            "MAX 1000",
        ],
        "maxes": [1000.0, 1000.0, 1000.0, 150.0, 200.0, 1000.0, 1000.0, 150.0, 1000.0, 1000.0, 1000.0],
    },
    {
        "id": "ash",
        "label_en": "Ash",
        "label_fa": "Ash",
        "unit": "%",
        "astm": "D-1506",
        "values": [
            "MAX 0.75",
            "MAX 0.75",
            "MAX 0.75",
            "MAX 0.15",
            "MAX 0.30",
            "MAX 0.75",
            "MAX 0.75",
            "MAX 0.30",
            "MAX 0.75",
            "MAX 0.75",
            "MAX 0.75",
        ],
        "maxes": [0.75, 0.75, 0.75, 0.15, 0.30, 0.75, 0.75, 0.30, 0.75, 0.75, 0.75],
    },
    {
        "id": "sulfur",
        "label_en": "Sulfur",
        "label_fa": "Sulfur",
        "unit": "%",
        "astm": "D-1619",
        "values": [
            "MAX 2.0",
            "MAX 2.0",
            "MAX 2.0",
            "MAX 0.15",
            "MAX 1.0",
            "MAX 2.0",
            "MAX 2.0",
            "MAX 1.0",
            "MAX 2.0",
            "MAX 2.0",
            "MAX 2.0",
        ],
        "maxes": [2.0, 2.0, 2.0, 0.15, 1.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0],
    },
    {
        "id": "n2_surface_area",
        "label_en": "N₂ Surface Area",
        "label_fa": "Nitrogen surface area",
        "unit": "m²/g",
        "astm": "D-6556",
        "values": [
            "73 / 83",
            "114 / 124",
            "109 / 119",
            "73.0 / 85.0",
            "71 / 86",
            "30 / 40",
            "35 / 45",
            "37 / 47",
            "88 / 98",
            "86 / 96",
            "73 / 83",
        ],
        "ranges": [
            (73.0, 83.0),
            (114.0, 124.0),
            (109.0, 119.0),
            (73.0, 85.0),
            (71.0, 86.0),
            (30.0, 40.0),
            (35.0, 45.0),
            (37.0, 47.0),
            (88.0, 98.0),
            (86.0, 96.0),
            (73.0, 83.0),
        ],
    },
    {
        "id": "pellet_hardness_avg",
        "label_en": "Individual Pellet Hardness — Average (20 pellets)",
        "label_fa": "Pellet hardness — mean (20 pellets)",
        "unit": "gf",
        "astm": "D-3313",
        "values": [
            "10 / 40",
            "10 / 40",
            "10 / 40",
            "10 / 50",
            "10 / 40",
            "10 / 40",
            "10 / 40",
            "10 / 40",
            "10 / 40",
            "10 / 40",
            "10 / 40",
        ],
        "ranges": [
            (10.0, 40.0),
            (10.0, 40.0),
            (10.0, 40.0),
            (10.0, 50.0),
            (10.0, 40.0),
            (10.0, 40.0),
            (10.0, 40.0),
            (10.0, 40.0),
            (10.0, 40.0),
            (10.0, 40.0),
            (10.0, 40.0),
        ],
    },
    {
        "id": "pellet_hardness_max",
        "label_en": "Individual Pellet Hardness — Maximum (20 pellets)",
        "label_fa": "Pellet hardness — max (20 pellets)",
        "unit": "gf",
        "astm": "D-3313",
        "values": ["50"] * 11,
        "maxes": [50.0] * 11,
    },
]


def build_product_catalog() -> dict[str, Any]:
    """Full catalog payload for API / dashboard."""
    products = []
    for idx, product in enumerate(CURRENT_PRODUCTS):
        specs = []
        for row in QUALITY_SPEC_ROWS:
            entry: dict[str, Any] = {
                "id": row["id"],
                "label_en": row["label_en"],
                "label_fa": row["label_fa"],
                "unit": row["unit"],
                "astm": row["astm"],
                "spec": row["values"][idx],
            }
            if "ranges" in row:
                lo, hi = row["ranges"][idx]
                entry["min"] = lo
                entry["max"] = hi
            if "nominals" in row:
                entry.update(row["nominals"][idx])
            if "mins" in row:
                entry["min"] = row["mins"][idx]
            if "maxes" in row:
                entry["max"] = row["maxes"][idx]
            specs.append(entry)
        products.append({**product, "quality_specs": specs})

    comparison = [
        {
            "id": row["id"],
            "label_fa": row["label_fa"],
            "label_en": row["label_en"],
            "unit": row["unit"],
            "astm": row["astm"],
            "by_grade": {
                CURRENT_PRODUCTS[i]["code"]: row["values"][i] for i in range(len(CURRENT_PRODUCTS))
            },
        }
        for row in QUALITY_SPEC_ROWS
    ]

    return {
        "source": "Shokrban current production quality specification sheets",
        "count": len(products),
        "products": products,
        "comparison": comparison,
        "grade_codes": [p["code"] for p in products],
        "classifications": sorted({p["classification"] for p in products}),
    }


# Compact numeric targets used by anomaly / process control (from production sheets).
GRADE_TARGETS: dict[str, dict[str, tuple[float, float]]] = {
    "N110": {"iodine_absorption": (135, 150), "dbp_absorption": (110, 125), "surface_area": (125, 140)},
    "N115": {"iodine_absorption": (120, 135), "dbp_absorption": (108, 122), "surface_area": (115, 130)},
    "N220": {
        "iodine_absorption": (116, 126),
        "dbp_absorption": (109, 119),
        "surface_area": (109, 119),
        "tint_strength": (111, 121),
    },
    "N234": {
        "iodine_absorption": (115, 125),
        "dbp_absorption": (120, 130),
        "surface_area": (114, 124),
        "tint_strength": (118, 128),
    },
    "N326": {
        "iodine_absorption": (77, 87),
        "dbp_absorption": (67, 77),
        "surface_area": (73, 83),
        "tint_strength": (106, 116),
    },
    "P8201": {
        "iodine_absorption": (25, 35),
        "dbp_absorption": (95, 110),
        "surface_area": (73, 85),
        "tint_strength": (99, 109),
    },
    "N330": {
        "iodine_absorption": (77, 87),
        "dbp_absorption": (97, 107),
        "surface_area": (73, 83),
        "tint_strength": (99, 109),
    },
    "N330-SV": {
        "iodine_absorption": (75, 90),
        "dbp_absorption": (95, 110),
        "surface_area": (71, 86),
        "tint_strength": (99, 109),
    },
    "N339": {
        "iodine_absorption": (85, 95),
        "dbp_absorption": (115, 125),
        "surface_area": (86, 96),
        "tint_strength": (106, 116),
    },
    "N375": {
        "iodine_absorption": (85, 95),
        "dbp_absorption": (109, 119),
        "surface_area": (88, 98),
        "tint_strength": (109, 119),
    },
    "N347": {"iodine_absorption": (85, 95), "dbp_absorption": (115, 130), "surface_area": (82, 92)},
    "N550": {
        "iodine_absorption": (38, 48),
        "dbp_absorption": (116, 126),
        "surface_area": (35, 45),
        "tint_strength": (58, 68),
    },
    "N550-VJ": {
        "iodine_absorption": (40, 50),
        "dbp_absorption": (110, 125),
        "surface_area": (37, 47),
        "tint_strength": (58, 68),
    },
    "N660": {
        "iodine_absorption": (31, 41),
        "dbp_absorption": (85, 95),
        "surface_area": (30, 40),
        "tint_strength": (52, 65),
    },
    "N762": {"iodine_absorption": (25, 35), "dbp_absorption": (60, 75), "surface_area": (25, 35)},
    "N774": {"iodine_absorption": (25, 35), "dbp_absorption": (65, 80), "surface_area": (25, 35)},
    "N990": {"iodine_absorption": (5, 15), "dbp_absorption": (35, 50), "surface_area": (6, 14)},
}
