apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    access: proxy
    url: postgres:5432
    user: icb_admin
    isDefault: false
    editable: true
    jsonData:
      database: carbon_black
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: change_me_strong_password
